#!/usr/bin/env python
"""
This script will return the expt_id to use for the next experiment.

This script creates a record in the lab database.

Could be called multiple times to "reserve" experiment id if necessary
"""

from labdb import LabDB

def get_next_expt_id():
    db = LabDB()

    try:
        sql = "INSERT INTO experiments (expt_id) VALUES (NULL)"
        db.execute(sql)
        rows = db.execute('SELECT LAST_INSERT_ID()')
        expt_id, = rows[0]
        db.commit()
    except:
        db.rollback()
        expt_id = None

    db.close()

    return expt_id

def main():
    expt_id = get_next_expt_id()
    if expt_id is None:
        print "Error with lab database."
    else:
        print "Current expt_id is", expt_id

if __name__ == "__main__":
    main()
